from __future__ import annotations

import csv
import io
import json
from pathlib import Path

from .db import connect
from .ingest import initialize_demo

SAMPLE_DATE = "2026-01-15"
FIELDS = [
    "company",
    "role",
    "location",
    "work_model",
    "experience_requirement",
    "experience_evidence",
    "compensation",
    "benefits",
    "first_seen",
    "source_url",
    "score",
    "why_it_fits",
    "primary_concern",
]


def _pay(row) -> str:
    if not row["compensation_min"]:
        return "Not stated"
    upper = f"–${row['compensation_max']:,}" if row["compensation_max"] else ""
    return (
        f"{row['compensation_currency']} ${row['compensation_min']:,}{upper} "
        f"per {row['compensation_period']}"
    )


def sample_rows() -> list[dict[str, str | int]]:
    """Build a deterministic public sample with no human-owned state or full descriptions."""
    db = connect(":memory:")
    try:
        initialize_demo(db)
        rows = db.execute("SELECT * FROM jobs WHERE active=1 ORDER BY score DESC,company,title")
        output = []
        for row in rows:
            experience = json.loads(row["experience_evidence"] or "[]")
            why = json.loads(row["why"] or "[]")
            concerns = json.loads(row["concerns"] or "[]")
            benefits = json.loads(row["benefits"] or "[]")
            output.append(
                {
                    "company": row["company"],
                    "role": row["title"],
                    "location": row["location"],
                    "work_model": row["workplace"] or "Not stated",
                    "experience_requirement": (
                        f"{row['experience_min']}+ years"
                        if row["experience_min"] is not None
                        else "Not stated"
                    ),
                    "experience_evidence": experience[0]["quote"] if experience else "Not stated",
                    "compensation": _pay(row),
                    "benefits": ", ".join(benefits) if benefits else "Not stated",
                    "first_seen": SAMPLE_DATE,
                    "source_url": row["source_url"] or "",
                    "score": row["score"],
                    "why_it_fits": "; ".join(why[:2]) if why else "Review the evidence",
                    "primary_concern": concerns[0] if concerns else "No obvious blocker",
                }
            )
        return output
    finally:
        db.close()


def render_csv(rows: list[dict]) -> str:
    buffer = io.StringIO(newline="")
    writer = csv.DictWriter(buffer, fieldnames=FIELDS, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue()


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(rows: list[dict]) -> str:
    lines = [
        "# Sample roles pulled in 2026",
        "",
        "This is a static, fictional product sample generated by `job-radar export-sample`.",
        "It contains role facts and ranking output only—never application status, notes, tags,",
        "contacts, personal configuration, or full job descriptions.",
        "",
        "| Company | Role | Location / work model | Experience | Compensation | Score | Why / concern |",
        "|---|---|---|---|---|---:|---|",
    ]
    for row in rows:
        why_concern = f"{row['why_it_fits']} **Concern:** {row['primary_concern']}"
        values = (
            row["company"],
            row["role"],
            f"{row['location']} · {row['work_model']}",
            row["experience_requirement"],
            row["compensation"],
            row["score"],
            why_concern,
        )
        lines.append("| " + " | ".join(_cell(value) for value in values) + " |")
    lines.extend(
        [
            "",
            "The companion [CSV](sample-roles-2026.csv) includes benefits, the supporting",
            "experience sentence, first-seen date, and fictional source URL for each row.",
            "",
        ]
    )
    return "\n".join(lines)


def write_sample_artifacts(output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    rows = sample_rows()
    csv_path = output_dir / "sample-roles-2026.csv"
    markdown_path = output_dir / "sample-roles-2026.md"
    csv_path.write_text(render_csv(rows))
    markdown_path.write_text(render_markdown(rows))
    return csv_path, markdown_path
